name: Hello # ワークフロー名
on: # イベント
  workflow_dispatch:
      inputs:
        greeting: # 入力パラメータ名
          type: string
          default: Hello
          required: true
          description: A cheerful word
jobs:
  hello: # ジョブID
    runs-on: ubuntu-latest # ランナー
    steps:
      - run: echo "Hello, World" # シェルコマンド
      - uses: actions/checkout@v4 # アクションの呼び出し
