name: Manual # ワークフロー名
on: # イベント
  workflow_dispatch:
      inputs:
        greeting: # 入力パラメータ名
          type: string
          default: Hello
          required: true
          description: A cheerful word
jobs:
  hello: # ジョブID
    runs-on: ubuntu-latest # ランナー
    steps:
      - run: echo "${{ inputs.greeting }}" # 入力パラメータ「greeting」の参照
